/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/retro-microphone-f959ff09ca914ac383882cc836dfdd9c
Title: Retro Microphone
*/

import React, { useRef } from 'react'
import { useGLTF, Float } from '@react-three/drei'

function ProjectModel3(props) {
  const { nodes, materials } = useGLTF('./assets/retro_microphone.glb')
  return (
    <Float>
      <group {...props} dispose={null} scale={0.001} position={[0, 0.3, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mic_low_poly001_microphone_retro_0.geometry}
          material={materials.microphone_retro}
          rotation={[0, Math.PI, 0]}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('./assets/retro_microphone.glb')

export default ProjectModel3