/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/retro-microphone-f959ff09ca914ac383882cc836dfdd9c
Title: Retro Microphone
*/

import React, { useRef } from 'react'
import { useGLTF, Float } from '@react-three/drei'
import gsap from 'gsap'

function ProjectModel3(props) {
  const { nodes, materials } = useGLTF('./assets/retro_microphone.glb')
  const groupRef = useRef()

  return (
    <Float>
      <group 
        {...props} 
        ref={groupRef}
        dispose={null} 
        scale={0.001} 
        position={[0, 0.3, 0]}
        onPointerOver={(e) => {
          e.stopPropagation()
          document.body.style.cursor = 'pointer'
          gsap.to(groupRef.current.rotation, {
            y: '+=0.3',
            duration: 0.3,
            yoyo: true,
            repeat: 1,
            ease: 'power1.inOut'
          })
        }}
        onPointerOut={(e) => {
          e.stopPropagation()
          document.body.style.cursor = 'default'
          gsap.to(groupRef.current.rotation, {
            y: 0,
            duration: 0.3,
            ease: 'power1.inOut'
          })
        }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mic_low_poly001_microphone_retro_0.geometry}
          material={materials.microphone_retro}
          rotation={[0, Math.PI, 0]}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('./assets/retro_microphone.glb')

export default ProjectModel3