/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Float } from '@react-three/drei'

function ProjectModel2(props) {
  const { nodes, materials } = useGLTF('./assets/maillot.glb')
  return (
    <Float>
      <group {...props} dispose={null}
        position={[0, -0.7, 0]}
      >
        <group scale={0.2}>
          <primitive 
            object={nodes.Scene}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('./assets/maillot.glb')

export default ProjectModel2